version: '3.9'

services:
  power_systems_api:
    ports:
      # Exposes application port.
    - "8000:8000"
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      POWER_SYSTEMS_DATA_API_DEMONSTRATOR_RELOAD: "True"
